<?php
/**
 * @author    jan huang <bboyjanhuang@gmail.com>
 * @copyright 2018
 *
 * @see      https://www.github.com/fastdlabs
 * @see      http://www.fastdlabs.com/
 */

namespace FastD\Sentinel\Agent;


use FastD\Process\AbstractProcess;
use FastD\Sentinel\Subscription;
use swoole_process;

class SentinelAgent extends AbstractProcess
{
    public function configure(array $options = [])
    {
        return parent::configure($options); // TODO: Change the autogenerated stub
    }

    public function handle(swoole_process $swoole_process)
    {
        $subscription = new Subscription();

        $subscription->start();
    }
}